DESIGN_NAME: pll_top

# We list files explicitly to prevent wildcard expansion errors
VERILOG_FILES: 
  - dir::../src/pfd.v
  - dir::../src/loop_filter.v
  - dir::../src/dco_nco.v
  - dir::../src/divider.v
  - dir::../src/pll_top.v

CLOCK_PORT: sys_clk
CLOCK_PERIOD: 10.0 # In nanoseconds

# Placement density
FP_CORE_UTIL: 45

# PDN Settings (Optional, using your defaults)
FP_PDN_VOFFSET: 5
FP_PDN_HOFFSET: 5
FP_PDN_VWIDTH: 2
FP_PDN_HWIDTH: 2
FP_PDN_VPITCH: 30
FP_PDN_HPITCH: 30

# --- PDK CONFIGURATION ---

# Technology-Specific Configs
pdk::sky130*:
  FP_CORE_UTIL: 45
  CLOCK_PERIOD: 10.0
  scl::sky130_fd_sc_hs:
    CLOCK_PERIOD: 8
  scl::sky130_fd_sc_ls:
    MAX_FANOUT_CONSTRAINT: 5

pdk::gf180mcu*:
  CLOCK_PERIOD: 24.0
  FP_CORE_UTIL: 45
  MAX_FANOUT_CONSTRAINT: 4
  PL_TARGET_DENSITY: 0.5
